// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf691os3W8Pwr9JiNjPIZD6PmE6P4c2Xw',
    appId: '1:684029695607:web:16af44bb4f058fc6ad9872',
    messagingSenderId: '684029695607',
    projectId: 'lulus-app-f8e42',
    authDomain: 'lulus-app-f8e42.firebaseapp.com',
    storageBucket: 'lulus-app-f8e42.appspot.com',
    measurementId: 'G-CLNW3V0TLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOq3LmiU59KB1qGFZTqGo8deIrcekqbo0',
    appId: '1:684029695607:android:f158d0893f32a84ead9872',
    messagingSenderId: '684029695607',
    projectId: 'lulus-app-f8e42',
    storageBucket: 'lulus-app-f8e42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCECZnA9mcdz75e5618NJ0Xcq3PwY-nNc0',
    appId: '1:684029695607:ios:585171aba2073473ad9872',
    messagingSenderId: '684029695607',
    projectId: 'lulus-app-f8e42',
    storageBucket: 'lulus-app-f8e42.appspot.com',
    iosClientId: '684029695607-h63egj7qngg9hvk26amc90bck8uo7ft5.apps.googleusercontent.com',
    iosBundleId: 'com.example.luluApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCECZnA9mcdz75e5618NJ0Xcq3PwY-nNc0',
    appId: '1:684029695607:ios:585171aba2073473ad9872',
    messagingSenderId: '684029695607',
    projectId: 'lulus-app-f8e42',
    storageBucket: 'lulus-app-f8e42.appspot.com',
    iosClientId: '684029695607-h63egj7qngg9hvk26amc90bck8uo7ft5.apps.googleusercontent.com',
    iosBundleId: 'com.example.luluApp',
  );
}
